#!/usr/bin/env python3
"""
Management & Generator Engine for Noctalia Restic Plugin (firo1919/restic).
Features:
- Reads/writes standard XDG configuration (~/.config/noctalia-restic/config.json)
- Dynamically generates ~/.local/share/noctalia-restic/runner.sh with notify-send alerts
- Dynamically generates and manages systemd units (~/.config/systemd/user/noctalia-restic.{service,timer})
- Caches cloud snapshots and performs safe non-destructive restores into ~/Restored/
- Tracks zero-network status in ~/.local/state/noctalia-restic/status.json
- Detects repository locks locally and via cloud query
"""

import sys
import shlex
import os
import json
import time
import shutil
import subprocess

CONFIG_DIR = os.path.expanduser("~/.config/noctalia-restic")
CONFIG_FILE = os.path.join(CONFIG_DIR, "config.json")

DATA_DIR = os.path.expanduser("~/.local/share/noctalia-restic")
RUNNER_SCRIPT = os.path.join(DATA_DIR, "runner.sh")

CACHE_DIR = os.path.expanduser("~/.cache/noctalia-restic")
SNAPSHOTS_CACHE = os.path.join(CACHE_DIR, "snapshots.json")

STATE_DIR = os.path.expanduser("~/.local/state/noctalia-restic")
STATUS_FILE = os.path.join(STATE_DIR, "status.json")

SYSTEMD_DIR = os.path.expanduser("~/.config/systemd/user")
SERVICE_FILE = os.path.join(SYSTEMD_DIR, "noctalia-restic.service")
TIMER_FILE = os.path.join(SYSTEMD_DIR, "noctalia-restic.timer")

SCRIPT_PATH = os.path.abspath(__file__)

DEFAULT_CONFIG = {
    "version": 1,
    "repository": "rclone:EncryptedGoogleDrive:Backups",
    "password_command": "rbw get restic-pass",
    "sources": [
        os.path.expanduser("~/Personal")
    ],
    "excludes": [
        "**/.cache",
        "**/node_modules",
        "**/target",
        "**/.venv",
        "**/.git/objects"
    ],
    "schedule": {
        "preset": "daily_03",
        "on_calendar": "*-*-* 03:00:00",
        "persistent": True
    },
    "retention": {
        "keep_daily": 7,
        "keep_weekly": 4,
        "keep_monthly": 6,
        "auto_prune": False
    }
}

SCHEDULE_PRESETS = {
    "daily_03": "*-*-* 03:00:00",
    "daily_22": "*-*-* 22:00:00",
    "every_6h": "00/6:00:00",
    "twice_daily": "*-*-* 03,15:00:00",
    "manual": ""
}

def load_config():
    os.makedirs(CONFIG_DIR, exist_ok=True)
    if os.path.isfile(CONFIG_FILE):
        try:
            with open(CONFIG_FILE) as f:
                data = json.load(f)
            for k, v in DEFAULT_CONFIG.items():
                if k not in data:
                    data[k] = v
            return data
        except Exception:
            pass
    with open(CONFIG_FILE, "w") as f:
        json.dump(DEFAULT_CONFIG, f, indent=2)
    return DEFAULT_CONFIG

def save_config(cfg_data):
    os.makedirs(CONFIG_DIR, exist_ok=True)
    with open(CONFIG_FILE, "w") as f:
        json.dump(cfg_data, f, indent=2)

def generate_runner_script(cfg):
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(STATE_DIR, exist_ok=True)

    sources_str = " ".join([shlex.quote(os.path.expanduser(s)) for s in cfg.get("sources", [])])
    excludes_args = " ".join([f'--exclude={shlex.quote(e)}' for e in cfg.get("excludes", [])])

    retention = cfg.get("retention", {})
    keep_daily = retention.get("keep_daily", 7)
    keep_weekly = retention.get("keep_weekly", 4)
    keep_monthly = retention.get("keep_monthly", 6)
    auto_prune = retention.get("auto_prune", False)
    prune_flag = "--prune" if auto_prune else ""

    content = f"""#!/usr/bin/env bash
# Auto-generated by Noctalia Restic Plugin on {time.strftime('%Y-%m-%d %H:%M:%S')}
# Do not edit manually; configure via Noctalia Dashboard or ~/.config/noctalia-restic/config.json
set -uo pipefail
umask 077

export RESTIC_REPOSITORY={shlex.quote(cfg.get('repository', ''))}
export RESTIC_PASSWORD_COMMAND={shlex.quote(cfg.get('password_command', ''))}

MANAGE_SCRIPT="{SCRIPT_PATH}"

record_status() {{
  local exit_code=$?
  python3 "$MANAGE_SCRIPT" record-status "$exit_code" 2>/dev/null || true
}}
trap record_status EXIT

echo "Starting Noctalia Restic Backup: {time.strftime('%Y-%m-%d %H:%M:%S')}"

# Execute backup
restic backup {excludes_args} {sources_str}

# Apply retention policy
restic forget \\
  --keep-daily {keep_daily} \\
  --keep-weekly {keep_weekly} \\
  --keep-monthly {keep_monthly} \\
  {prune_flag}

echo "Finished Noctalia Restic Backup: $(date)"
"""
    with open(RUNNER_SCRIPT, "w") as f:
        f.write(content)
    os.chmod(RUNNER_SCRIPT, 0o755)

def generate_systemd_units(cfg):
    os.makedirs(SYSTEMD_DIR, exist_ok=True)

    service_content = f"""[Unit]
Description=Noctalia Automated Restic Backup
Documentation=https://github.com/firo1919/noctalia-restic
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart={RUNNER_SCRIPT}
Nice=19
IOSchedulingClass=best-effort
IOSchedulingPriority=7
"""
    with open(SERVICE_FILE, "w") as f:
        f.write(service_content)

    schedule = cfg.get("schedule", {})
    on_calendar = schedule.get("on_calendar", "*-*-* 03:00:00")
    preset = schedule.get("preset", "daily_03")

    if preset != "manual" and on_calendar:
        timer_content = f"""[Unit]
Description=Run Noctalia Restic Backup Periodically

[Timer]
OnCalendar={on_calendar}
RandomizedDelaySec=10m
Persistent=true

[Install]
WantedBy=timers.target
"""
        with open(TIMER_FILE, "w") as f:
            f.write(timer_content)

        subprocess.run(["systemctl", "--user", "daemon-reload"], check=True)
        subprocess.run(["systemctl", "--user", "enable", "--now", "noctalia-restic.timer"], check=True)
    else:
        subprocess.run(["systemctl", "--user", "daemon-reload"], check=True)
        subprocess.run(["systemctl", "--user", "disable", "--now", "noctalia-restic.timer"], stderr=subprocess.DEVNULL)
        if os.path.exists(TIMER_FILE):
            os.remove(TIMER_FILE)

def cmd_record_status(exit_code_str):
    exit_code = 0
    try:
        exit_code = int(exit_code_str)
    except ValueError:
        exit_code = 1

    cfg = load_config()
    os.makedirs(STATE_DIR, exist_ok=True)

    status = "success" if exit_code == 0 else "failed"

    status_data = {
        "last_backup_epoch": int(time.time()),
        "last_backup_time": time.strftime("%Y-%m-%d %H:%M:%S"),
        "status": status,
        "exit_code": exit_code,
        "repository": cfg.get("repository", ""),
        "sources": cfg.get("sources", [])
    }

    with open(STATUS_FILE, "w") as f:
        json.dump(status_data, f, indent=2)

    if exit_code == 0:
        subprocess.run(
            ["notify-send", "Restic Cloud Backup", "Backup completed successfully.", "-a", "Noctalia"],
            stderr=subprocess.DEVNULL
        )
        # Refresh snapshot cache in background
        try:
            cmd_fetch_snapshots()
        except Exception:
            pass
    else:
        subprocess.run(
            ["notify-send", "Restic Cloud Backup", f"Backup failed (exit code {exit_code})! Check journal logs.", "-u", "critical", "-a", "Noctalia"],
            stderr=subprocess.DEVNULL
        )

def cmd_install():
    cfg = load_config()
    generate_runner_script(cfg)
    generate_systemd_units(cfg)
    print(json.dumps({
        "ok": True,
        "message": "Runner script and systemd units generated and enabled successfully.",
        "runner": RUNNER_SCRIPT,
        "service": SERVICE_FILE,
        "timer": TIMER_FILE
    }))

def cmd_fetch_snapshots():
    os.makedirs(CACHE_DIR, exist_ok=True)
    cfg = load_config()
    repo = cfg.get("repository", "")
    pwd_cmd = cfg.get("password_command", "")

    cmd = [
        "restic", "snapshots",
        "-r", repo,
        "--password-command", pwd_cmd,
        "--json"
    ]

    try:
        res = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        if res.returncode == 0:
            data = json.loads(res.stdout)
            with open(SNAPSHOTS_CACHE, "w") as f:
                json.dump(data, f, indent=2)
            print(json.dumps({"ok": True, "count": len(data), "cached_at": int(time.time())}))
            return
        else:
            print(json.dumps({"ok": False, "error": res.stderr.strip()}))
            return
    except Exception as e:
        print(json.dumps({"ok": False, "error": str(e)}))

def cmd_restore(snapshot_id):
    if not snapshot_id:
        print(json.dumps({"ok": False, "error": "Missing snapshot ID"}))
        return

    cfg = load_config()
    repo = cfg.get("repository", "")
    pwd_cmd = cfg.get("password_command", "")

    timestamp_str = time.strftime("%Y-%m-%d-%H%M")
    target_dir = os.path.expanduser(f"~/Restored/{timestamp_str}-{snapshot_id[:8]}")
    os.makedirs(target_dir, exist_ok=True)

    cmd = [
        "restic", "restore", snapshot_id,
        "--target", target_dir,
        "-r", repo,
        "--password-command", pwd_cmd
    ]

    try:
        res = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
        if res.returncode == 0:
            print(json.dumps({
                "ok": True,
                "snapshot_id": snapshot_id,
                "target": target_dir,
                "message": f"Snapshot #{snapshot_id[:8]} restored safely to {target_dir}"
            }))
        else:
            print(json.dumps({"ok": False, "error": res.stderr.strip()}))
    except Exception as e:
        print(json.dumps({"ok": False, "error": str(e)}))

def cmd_check_lock():
    try:
        j = subprocess.run(
            ["journalctl", "--user", "-u", "noctalia-restic.service", "-n", "15", "--no-pager"],
            capture_output=True,
            text=True,
            timeout=2
        )
        if "already locked" in j.stdout or "unable to create lock" in j.stdout:
            print(json.dumps({"ok": True, "locked": True, "reason": "Repository lock error detected in recent logs"}))
            return
    except Exception:
        pass

    cfg = load_config()
    repo = cfg.get("repository", "")
    pwd_cmd = cfg.get("password_command", "")
    cmd = ["restic", "list", "locks", "-r", repo, "--password-command", pwd_cmd]
    try:
        res = subprocess.run(cmd, capture_output=True, text=True, timeout=20)
        locks = [line.strip() for line in res.stdout.splitlines() if line.strip() and not line.startswith("repository ")]
        is_locked = len(locks) > 0
        print(json.dumps({"ok": True, "locked": is_locked, "locks": locks}))
    except Exception as e:
        print(json.dumps({"ok": False, "locked": False, "error": str(e)}))

def cmd_status():
    if os.path.isfile(STATUS_FILE):
        try:
            with open(STATUS_FILE) as f:
                data = json.load(f)
            data["ok"] = True
            print(json.dumps(data))
            return
        except Exception:
            pass
    print(json.dumps({"ok": False, "error": "No status file found"}))

def cmd_get_config():
    cfg = load_config()
    print(json.dumps(cfg))

def cmd_set_config(raw_json):
    try:
        data = json.loads(raw_json)
        save_config(data)
        generate_runner_script(data)
        generate_systemd_units(data)
        print(json.dumps({"ok": True, "message": "Configuration updated and systemd units re-applied."}))
    except Exception as e:
        print(json.dumps({"ok": False, "error": str(e)}))

def main():
    if len(sys.argv) < 2:
        print(json.dumps({"ok": False, "error": "Missing command argument"}))
        sys.exit(1)

    subcmd = sys.argv[1]
    if subcmd == "install":
        cmd_install()
    elif subcmd == "record-status":
        code = sys.argv[2] if len(sys.argv) > 2 else "0"
        cmd_record_status(code)
    elif subcmd == "fetch-snapshots":
        cmd_fetch_snapshots()
    elif subcmd == "restore":
        sid = sys.argv[2] if len(sys.argv) > 2 else ""
        cmd_restore(sid)
    elif subcmd == "check-lock":
        cmd_check_lock()
    elif subcmd == "status":
        cmd_status()
    elif subcmd == "get-config":
        cmd_get_config()
    elif subcmd == "set-config":
        raw = sys.argv[2] if len(sys.argv) > 2 else "{}"
        cmd_set_config(raw)
    else:
        print(json.dumps({"ok": False, "error": f"Unknown command '{subcmd}'"}))
        sys.exit(1)

if __name__ == "__main__":
    main()
